services:

# ======================================================================
# PHP 8.3.x
# ======================================================================

  php83fpm_01:
    image: keptcode/php83laravel:11.21.0
    container_name: laravel-php83fpm-01
    build:
      context: ./build
      dockerfile: Dockerfile
    working_dir: /usr/share/nginx/html
    restart: on-failure
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html/www
      - ./conf.d/php83.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - php83fpm_network

# ======================================================================
# Web Server
# ======================================================================

  nginx_01:
    image: nginx:1.27.1-alpine
    container_name: laravel-nginx-01
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=81
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html/www
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/localhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php83fpm_01:php83fpm"
    ports:
      - "80:80"
    networks:
      - php83fpm_network

networks:
  php83fpm_network:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.10.0.0/24
#          gateway: 172.10.0.1